;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32vn-iot-uno]
platform = https://github.com/tasmota/platform-espressif32/releases/download/2025.04.30/platform-espressif32.zip
board = esp32vn-iot-uno
framework = arduino

monitor_speed = 115200
; upload_port = COM[4] ; User can define this locally
board_build.f_cpu = 240000000L
board_build.partitions = min_spiffs.csv
board_build.filesystem = littlefs

lib_deps =
     bblanchon/ArduinoJson@7.0.4
     SpeedyStepper
     teemuatlut/TMCStepper
     ESP32Async/ESPAsyncWebServer
     ESP32Async/AsyncTCP
     ayushsharma82/ElegantOTA
     knolleary/PubSubClient@2.8
